arch:
  [
    "cortex-m0",
    "cortex-m0plus",
    "cortex-m1",
    "cortex-m3",
    "cortex-m4",
    "cortex-m4f",
    "cortex-m7",
    "cortex-m7f",
    "cortex-m7d",
    "cortex-m23",
    "cortex-m33",
    "cortex-m33f",
    "cortex-m35pf",
    "cortex-m55",
    "cortex-m85",
  ]

# Obsolete but kept for backwards compatibility
libc: [null, "default", "custom"]
